version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: activity
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
